"""Domain models for the conversation and the support assistant contract."""

from typing import Literal

from pydantic import BaseModel, Field

Role = Literal["system", "user", "assistant"]


class Message(BaseModel):
    role: Role
    content: str = Field(min_length=1)


Action = Literal[
    "check_order_status",
    "check_payment_history",
    "refund_order",
    "reset_password",
    "update_account_details",
    "request_more_information",
    "share_help_article",
    "escalate_to_human",
]


class SupportAnswer(BaseModel):
    """What the model generates. Used as the Structured Outputs schema."""

    answer: str = Field(min_length=1, description="Concise reply for the support agent.")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Self-estimated confidence that the answer is correct, from 0 to 1.",
    )
    actions: list[Action] = Field(
        description="Recommended next steps for the support agent, chosen from the catalog.",
    )


class Metrics(BaseModel):
    """What our code measures after the call. Never generated by the model."""

    prompt_tokens: int = Field(ge=0)
    completion_tokens: int = Field(ge=0)
    total_tokens: int = Field(ge=0)
    latency_ms: float = Field(ge=0)
    estimated_cost_usd: float = Field(ge=0)


class SupportResponse(SupportAnswer):
    """Final JSON contract returned to downstream systems."""

    metrics: Metrics
